;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-set-rectangle-mark
        evil-numbers/dec-at-pt
        evil-numbers/inc-at-pt
        ignore
        tab-to-tab-stop
        ))

(setq mc/cmds-to-run-once
      '(
        ))
